### PR TITLE
recommended Cyann

### PR DESCRIPTION
**Pull request by Howard-Zhou**
Cyann is a lightweight learning management system built by a group of UBC students

### CODE REVIEW

**Comment by dohliam** [comment]
Hi Howard, thanks for the PR! This looks like a great project. I noticed that there is no license file included in the linked repo, so it wasn't possible to confirm that this is in fact FOSS... if you could add a license file we'd be happy to include it in the list! :smile:

**Comment by Howard-Zhou** [comment]
Hi sorry for the late response. My team and I are a little busy because of the finals, but we discussed and decided to use MIT License for our project. The license is added to the repo, you can check it out:thumbsup:

Thank you very much

**Comment by darshandsoni** [comment]
Great project @Howard-Zhou! We do always encourage devs to put up a licence in there so that people know the terms of use. Nice to see good old MIT there. I will merge it!

**Comment by darshandsoni** [comment]
Great project @Howard-Zhou! We do always encourage devs to put up a licence in there so that people know the terms of use. Nice to see good old MIT there. Time to merge it!

**Pull request merged**
